### ISSUE TITLE
编译X3的包会卡住

### ISSUE THREAD

**Issue by 63isOK** [HorizonRDK/robot_dev_config#59]
![image](https://github.com/HorizonRDK/robot_dev_config/assets/45553405/6c328eee-61a9-4e2b-80bd-0a4aa68cdbc1)

按照文档执行, 最后生成X3的包时会卡住, 多次尝试均卡在foonathan_memory_vendor的12%, 卡住的时间会超过10分钟.

```
bash robot_dev_config/build.sh -p X3
```

**Comment by zhukao** [comment]
docker里面编译的吗，代码也是在docker里拉取的吗？

**Comment by 63isOK** [comment]
@zhukao 是的, 在docker里面

**Comment by zhukao** [comment]
> 

编译这个pkg的时候，CMakeLists.txt中会下载另一个repo（https://github.com/foonathan/memory.git），下载到build/foonathan_memory_vendor/foo_mem-ext-prefix/src/foo_mem-ext，看下这个路径下有没有这个repo。
如果没有的话，可能是访问github网络不稳定等原因，尝试一些加速方法如fastgithub等。

**Comment by 63isOK** [comment]
@zhukao 感谢提醒, 挂梯子后,所有步骤重新来一次未遇到报错,一次成功.
